# Numpy Array

In [2]:
import numpy as np

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [17]:
np.linspace(0,20,30)

array([ 0.        ,  0.68965517,  1.37931034,  2.06896552,  2.75862069,
        3.44827586,  4.13793103,  4.82758621,  5.51724138,  6.20689655,
        6.89655172,  7.5862069 ,  8.27586207,  8.96551724,  9.65517241,
       10.34482759, 11.03448276, 11.72413793, 12.4137931 , 13.10344828,
       13.79310345, 14.48275862, 15.17241379, 15.86206897, 16.55172414,
       17.24137931, 17.93103448, 18.62068966, 19.31034483, 20.        ])

In [20]:
 np.array([[5,10,15],[20,25,30],[35,40,45]])

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
scores = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [25]:
print(scores)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [40]:
scores[:,:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [39]:
scores[1:,1:]

array([[25, 30],
       [40, 45]])

In [43]:
class_scores = np.array([[7,0,10,20],[5,1,40,200],[1,1,4,30]])

In [44]:
print(class_scores)

[[  7   0  10  20]
 [  5   1  40 200]
 [  1   1   4  30]]


In [51]:
class_scores[:,2:3]

array([[10],
       [40],
       [ 4]])

In [52]:
array1 = np.array([[7,0],[10,20]])

In [54]:
array2 = np.array([[5,1],[40,200]])

In [55]:
array1 + array2 

array([[ 12,   1],
       [ 50, 220]])

In [56]:
array1 / array2

array([[1.4 , 0.  ],
       [0.25, 0.1 ]])

In [57]:
array1**2

array([[ 49,   0],
       [100, 400]], dtype=int32)

In [59]:
class_scores.transpose()

array([[  7,   5,   1],
       [  0,   1,   1],
       [ 10,  40,   4],
       [ 20, 200,  30]])

In [61]:
scores_1 = np.array([1,3,-2,-5,6,8,9])

In [62]:
scores_1.sort()

In [63]:
scores_1

array([-5, -2,  1,  3,  6,  8,  9])

In [64]:
class_scores.sort()

In [65]:
class_scores

array([[  0,   7,  10,  20],
       [  1,   5,  40, 200],
       [  1,   1,   4,  30]])

In [70]:
array3 = np.arange(5,14)

In [71]:
array3

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

In [72]:
array3.reshape(3,3)

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [78]:
array3.transpose()

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

In [1]:
import numpy as np

In [2]:
a = np.arange(10,19).reshape(3,3)

In [3]:
a

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [4]:
# Iterating through an array uses the for loop
for i in a:
    print(i)

[10 11 12]
[13 14 15]
[16 17 18]


In [5]:
for item in a.flat:
    print(item)

10
11
12
13
14
15
16
17
18


# apply_along_axis funtion helps u to apply a function on a row or column. if the axis = 0; then it iterates the column. if axis = 1; then it iterates the rows.


In [7]:
np.apply_along_axis(np.mean, axis = 0, arr = a)

array([13., 14., 15.])

In [8]:
np.apply_along_axis(np.mean, axis = 1, arr = a)

array([11., 14., 17.])

In [14]:
def fap(x):
    return x/2

In [15]:
np.apply_along_axis(fap, axis = 1, arr = a)

array([[5. , 5.5, 6. ],
       [6.5, 7. , 7.5],
       [8. , 8.5, 9. ]])

In [17]:
b = np.random.random((4,4))

In [18]:
b

array([[0.84973069, 0.98051712, 0.71556624, 0.99639854],
       [0.42078237, 0.79888009, 0.72965676, 0.14322794],
       [0.94581216, 0.13545886, 0.82029864, 0.18042381],
       [0.68747176, 0.57235159, 0.81559991, 0.14580761]])

In [19]:
b > 0.5

array([[ True,  True,  True,  True],
       [False,  True,  True, False],
       [ True, False,  True, False],
       [ True,  True,  True, False]])

In [20]:
b[b>0.5]

array([0.84973069, 0.98051712, 0.71556624, 0.99639854, 0.79888009,
       0.72965676, 0.94581216, 0.82029864, 0.68747176, 0.57235159,
       0.81559991])

# Joining arrays

In [22]:
a = np.ones((3,3))
b = np.zeros((3,3))

In [24]:
# joining vertically; column by column
np.vstack((a, b))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
# joining horizontally; row by row
np.hstack((a, b))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [26]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

In [28]:
np.column_stack((a,b,c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [29]:
np.row_stack((a,b,c))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
# splitting arrays
a = np.arange(16).reshape((4,4))

In [31]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [34]:
[b, c] = np.hsplit(a, 2) 

In [35]:
b

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [36]:
c

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [37]:
[b, c] = np.vsplit(a, 2)

In [38]:
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [40]:
c

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
# copy arrays
a = np.array([1,2,3,4])

In [42]:
a

array([1, 2, 3, 4])

In [44]:
b = np.copy(a)

In [45]:
b

array([1, 2, 3, 4])

In [47]:
# generating a random whole number from 1 - 10
x = np.random.randint(10)

In [48]:
x

4

In [49]:
# Generating a random float from 0 to 1:
y = np.random.rand()

In [50]:
y

0.6983351204617229

In [51]:
# random numbers with a specified size
x = np.random.randint(20, size = 9)

In [52]:
x

array([12,  7, 18, 10,  6,  5, 19,  6,  2])

In [53]:
x.reshape(3,3)

array([[12,  7, 18],
       [10,  6,  5],
       [19,  6,  2]])

In [54]:
y = np.random.randint(100, size= (3,4))

In [55]:
y

array([[18, 93, 60, 82],
       [97, 40, 78, 27],
       [74, 95, 51, 68]])

In [56]:
z = np.random.rand(3,3)

In [57]:
z

array([[0.5467042 , 0.48874006, 0.65725457],
       [0.73510156, 0.48090283, 0.75259317],
       [0.5465017 , 0.24608715, 0.19497075]])

# generating an array of randomly picked numbers from the given array with their respective probability outcome


In [59]:
a

array([4, 9, 6, 4, 9, 6, 4, 7, 7, 7, 9, 6, 6, 9, 7, 9, 9, 9, 9, 7])

In [61]:
a = np.random.choice([2,4,7,9,6], p = [0, 0.1, 0.3, 0.5, 0.1], size = (20))

In [62]:
b = a = np.random.choice([2,4,7,9,6], p = [0, 0.1, 0.3, 0.5, 0.1], size = (4,4))

In [63]:
b

array([[9, 9, 7, 4],
       [6, 9, 9, 6],
       [7, 6, 7, 9],
       [7, 6, 6, 9]])

# Numpy permutations
A permutation refers to an arrangement of elements.

In [64]:
# Random shuffle
arr = np.array([2,4,6,7,9])

In [66]:
 np.random.shuffle(arr)

In [67]:
arr

array([9, 4, 7, 2, 6])

In [68]:
a = np.array([23,34,54,22,99])

In [70]:
np.random.permutation(a)

array([22, 54, 23, 34, 99])